#!/bin/bash
########################################
#                                      #
# From:	   Robert Bruckmueller         #
# Email:   admin@mediadelivery.de      #
# Web:     mediadelivery.de            #
# Version: 1.6.0                       #
# Date:    14.11.14                    #
# License: GPL v3                      #
# http://www.gnu.org/copyleft/gpl.html #
#                                      #
########################################

################################
#                              #
# Config at apt-check.config   #
#                              #
################################

source apt-check.config

hash mutt 2>/dev/null || { echo >&2 "I require mutt but it's not installed.  Aborting."; exit 1; }

if [ $1 ]
then
	logdebug=true
else
	logdebug=false
fi
servername=`hostname -f`
senemail() {
	betreff=$1
	body=$2
	if [ $body = "yes" ]
	then
		attach=true
	fi
	if [ -z $attach ]
	then
		if [ -z $emailuser ]
		then
			if mutt -e "set smtp_url=smtp://${emailsmtp}:${emailport}" -e "set ssl_starttls=$emailtls" -e "set from=$emailfrom" -s "$betreff" -- $emailto <<< "$body"
			then
				debugpost "Email wurde gesendet."
			else
				echo "Es gab ein Problem mit mutt. Bitte Prüfen Sie die Config."
				exit 1
			fi
		else
		    if mutt -e "set smtp_url=smtp://${emailuser}@${emailsmtp}:${emailport}" -e "set ssl_starttls=$emailtls" -e "set smtp_pass=$emailpass" -e "set from=$emailfrom" -s "$betreff" -- $emailto <<< "$body"
			then
				debugpost "Email wurde gesendet."
			else
				echo "Es gab ein Problem mit mutt. Bitte Prüfen Sie die Config."
				exit 1
			fi
		fi
	else
		if [ -z $emailuser ]
		then
        	if mutt -e "set smtp_url=smtp://${emailsmtp}:${emailport}" -e "set ssl_starttls=$emailtls" -e "set from=$emailfrom" -s "$betreff" -- $emailto < /tmp/apt-check
        	then
				debugpost "Email wurde gesendet."
			else
				echo "Es gab ein Problem mit mutt. Bitte Prüfen Sie die Config."
				exit 1
			fi
		else
        	if mutt -e "set smtp_url=smtp://${emailuser}@${emailsmtp}:${emailport}" -e "set ssl_starttls=$emailtls" -e "set smtp_pass=$emailpass" -e "set from=$emailfrom" -s "$betreff" -- $emailto < /tmp/apt-check 
        	then
				debugpost "Email wurde gesendet."
			else
				echo "Es gab ein Problem mit mutt. Bitte Prüfen Sie die Config."
				exit 1
			fi
		fi
	fi
}

debugpost(){
	text=$1
	if [ $logdebug = true ]
    then
    	echo $text
    fi
}

if [ -f /tmp/apt-check.tmp ]
then
	oldanz=`cat /tmp/apt-check.tmp`
else
	oldanz=0
fi

if apt-get update -qq
then
        anz=`apt-get upgrade -V --assume-no | tail -n+5 | wc -l`
        if [ $anz -gt 0 ] && [ $anz != $oldanz ]
        then
                debugpost "Es stehen Updates auf dem System $servername zur Verfuegung" 
                echo "Es stehen folgende Updates auf dem System $servername zur Verfuegung:" > /tmp/apt-check

                apt-get upgrade -V --assume-no | tail -n+5 | head -n-2 >> /tmp/apt-check
                senemail "APT-Check: Updates fuer $servername" "yes"
                rm /tmp/apt-check
				echo $anz > /tmp/apt-check.tmp
		elif [ $anz -gt 0 ] && [ $anz == $oldanz ]
		then
			debugpost "Updaes Verfuegbar eine Email wurde bereits gesendet"
			exit 0
		else
			debugpost "Keine Updates"
			exit 0
		fi
else
	debugpost "apt-get update Fehler"
	senemail "APT-Check: Fehler auf $servername" "Es ist ein Fehler bei apt-get aufgetreten."
fi
